<template>
	<div class="credits">
		<div class="wrapper" :style="{ 'animation-duration': animationDuration }">
			<h2></h2>
 
			<div v-if="parcours === 'conducteur'">			
						<p><em>Ce projet a été conçu par six étudiants de l’École de journalisme de Sciences Po :</em></p>
						<p><strong>Enquête</strong><br>
						Tamara Bouhl, Mathilde Dumazet, Aurore Gayte & Mathilde Saliou</p>
						<p><strong>Code</strong><br>
						Lawrence Bekk-Day & Océane Cornevin
						<p><strong>Remerciements tout particuliers à</strong><br>
							Julie Zentkowski pour le graphisme<br>
							Jules Bonnard (AFP) & Pierre Romera (ICIJ) pour leur accompagnement<br>
						Célia Mériguet & Thibaud Vuitton (franceinfo) pour leurs conseils éditoriaux</p>
						<p><strong>Crédits supplémentaires</strong><br>
						Google Maps, © 2017<br>

						Icône « iMac » par Vladimir Belochkin, de thenounproject.com</p>
						<p><small>© 2018 Tous droits réservés</small></p>
			</div>
			<div v-else-if="parcours === 'musicien'">			
						<p><em>Ce projet a été conçu par six étudiants de l’École de journalisme de Sciences Po :</em></p>
						<p><strong>Enquête</strong><br>
						Tamara Bouhl, Mathilde Dumazet, Aurore Gayte & Mathilde Saliou</p>
						<p><strong>Code</strong><br>
						Lawrence Bekk-Day & Océane Cornevin
						<p><strong>Remerciements tout particuliers à</strong><br>
							Julie Zentkowski pour le graphisme<br>
							Jules Bonnard (AFP) & Pierre Romera (ICIJ) pour leur accompagnement<br>
						Célia Mériguet & Thibaud Vuitton (franceinfo) pour leurs conseils éditoriaux</p>
						<p><strong>Remerciements</strong><br>
						Robin Meier, Daniele Ghisi, João Felipe, Anthony Rival, Dipty Chander</p>
						<p><strong>Crédits supplémentaires</strong><br>
						<i>Hello Shadow</i><br>
						Composed by Stromae, SKYGGE, The Bionix with Flow Machines, inspired by Cape Verdian music, Audio stems generated: choirs, rhythm guitar, Lyrics: Kiesza<br>
						Vocals: Kiesza, All instruments performed by Stromae, The Bionix and SKYGGE<br>
						Mixed by Lionel Capouillez, Produced by The Bionix</p>
						<p><i>Sons NSynth</i><br>
						License / Copyright 2017 Google Inc.</p>
						<p><i>DeepBach: harmonization in the style of Bach generated using deep learning</i><br>
						DeepBach is developed by Gaëtan Hadjeres,  Sony CSL and LIP6 (UPMC/CNRS).<br>
						Performed by Emmanuel Deruty using Küng recorders. Flow Machines project is funded by the European<br> Research Council under the Seventh Framework Programme / ERC Grant Agreement n. 291156</p>
						<p><i>Daddy's Car: a song composed by Artificial Intelligence - in the style of the Beatles</i><br>
						Composed with Flow Machines and 45 songs of The Beatles. Scientists at SONY CSL Research Lab  have created the first-ever entire songs composed by Artificial Intelligence: "Daddy's Car" and "Mister Shadow".<br> "Daddy's Car"  is composed in the style of The Beatles. French composer Benoît Carré arranged and produced the songs, and wrote the lyrics.</p>
						<p><i>Jimmy O'Corlan</i><br>
						João Felipe, char-rnn composes Irish Folk music. Samples generated by char-rnn when trained on ~14k Irish Folk tunes (downloaded from thesession.org).<br>
						http://www.seaandsailor.com; https://twitter.com/seaandsailor</p>
						<p><i>As the lights fade out</i><br>
						Daniele Ghisi, Robin Meier, Commissioned by IRCAM-Centre Pompidou, Used, in part, in "La fabrique de monstres", a theatrical piece by Jean-François Peyret.<br>
						With the help of Philippe Esling, Léopold Créstel, Mattia Bergomi, Giorgio Presti, NaMi Lab<br>
						Obtained via a modified version of the SampleRNN model (Soroush Mehri et al. link), followed by a selection of results and a rough montage.</p>
						<p><i>La Marche Turque</i><br>
						W.A. Mozart</p>
						<p><i>Pierre et le Loup</i><br>
						Sergueï Prokofiev</p>
						<p>Icône « iMac » par Vladimir Belochkin, de thenounproject.com</p>
						<p>Emission SOFT POWER par Frédéric Martel et Zoé Sfez - France Culture<br>
						Invité François Pachet, Director of Spotify Creator Technology Research Lab<br>
						« À l'occasion des Grammys Awards 2018, Soft Power s'intéresse aux mutations du secteur musical et à l'impact de l'intelligence artificielle sur la création. L'IA remplacera-t-elle les artistes ? »<br>
						https://www.franceculture.fr/emissions/soft-power/soft-power-dimanche-28-janvier-2018</p>
						<p>Stromae et d'autres artistes composent "Hello World" avec... de l'intelligence artificielle<br>
						Par Culturebox (avec AFP) @Culturebox<br>
						https://culturebox.francetvinfo.fr/musique/evenements/stromae-et-kiesza-dans-un-album-realise-avec-de-l-intelligence-artificielle-266239</p>
						<p>Images Deep Dream générées à partir de http://psychic-vr-lab.com/deepdream/</p>
						<p>Icône « iMac » par Vladimir Belochkin, de thenounproject.com</p>
						<p><small>© 2018 Tous droits réservés</small></p>

			</div>
			<div v-else-if="parcours === 'juriste'">			
						<p><em>Ce projet a été conçu par six étudiants de l’École de journalisme de Sciences Po :</em></p>
						<p><strong>Enquête</strong><br>
						Tamara Bouhl, Mathilde Dumazet, Aurore Gayte & Mathilde Saliou</p>
						<p><strong>Code</strong><br>
						Lawrence Bekk-Day & Océane Cornevin
						<p><strong>Remerciements tout particuliers à</strong><br>
							Julie Zentkowski pour le graphisme<br>
							Jules Bonnard (AFP) & Pierre Romera (ICIJ) pour leur accompagnement<br>
						Célia Mériguet & Thibaud Vuitton (franceinfo) pour leurs conseils éditoriaux</p>
						<p><strong>Remerciements</strong><br>
						Jacques Levy-Vehel (co-fondateur de Case Law Analytics et chercheur à l'Institut national de recherche en informatique et en automatique)<br>
						Joachim Herrera (doctorant à l'Ecole de droit de Sciences Po)<br>
						Antoine Garapon (magistrat et juriste; Secrétaire général de l'Institut des hautes études sur la Justice)<br>
						Lise Damelet (avocate chez Orrick, Herrington & Sutcliffe, cofondatrice de l'Incubateur du barreau de Paris)<br>
						Dipty Chander (Présidente E-mma France)<br><br>

						Icône « iMac » par Vladimir Belochkin, de thenounproject.com</p>
						<p><small>© 2018 Tous droits réservés</small></p>
			</div>


			<div class="credits-footer">
				<div class="text-center mt-4">
					<router-link to="/" class="btn btn-primary">
						Refaire une partie
					</router-link>
				</div>
					<p><br>Partagez votre intelligence artificielle<br class="rwd-break"> avec vos amis !</p>
				<social-sharing inline-template class="mb-4">
					<div>
						<network network="facebook" class="btn btn-sm btn-default cursorhere">
						  <i class="fa fa-fw fa-facebook"></i> Facebook
						</network>
						<network network="twitter" class="btn btn-sm btn-default cursorhere">
						  <i class="fa fa-fw fa-twitter"></i> Twitter
						</network>
					</div>
				</social-sharing>
			</div>
		</div>
	</div>
</template>

<script>
module.exports = {
	name: 'credits',
	props: ['parcours'],
	computed: {
		animationDuration: function() {
			return ({
				'juriste': 17,
				'musicien': 30,
				'conducteur': 15
			}[this.parcours] || 30) + 's';
		}
	}
}
</script>

<style scoped>
.credits {
	position:absolute;
	top: 0;
	left: 50%;
	height: 100%;	
	width: 100%;
	max-width: 660px;
	transform: translateX(-50%);
	overflow: hidden;
}

.cursorhere {
	cursor: pointer;
}

.wrapper {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  font-size: 15px;
  text-align: center;
  animation: 30s credits linear forwards;
}

.credits-footer {
	position: absolute
	top:100%;
	left:0;
	width: 100%;
	padding: 10%;
	transform: translateY(100%);
	font-weight: bold;
}

@keyframes credits {
    0% { 
    	top:  100%;
    	transform: translateY(0);
    }
  	100% { 
  		top: 0; 
    	transform: translateY(-100%);
  	}

 .rwd-break { display: none; }
 }
</style>