<template>
	<div class="credits">
		<div class="wrapper" :style="{ 'animation-duration': animationDuration }">
			<h2>Credits</h2>

			<div v-if="parcours === 'conducteur'">			
				<p>
					GENERIQUE
					 </br>
					Graphisme : Julie Zentkowski
					 </br>
					 Merci tout particulièrement à Jules Bonnard et Pierre Romera de l'AFP pour leur aide précieuse en code
					 </br>
					Remerciements : Google Maps, © 2017
				</p>
			</div>
			<div v-else-if="parcours === 'musicien'">			
				<p> 
					GENERIQUE
					 </br>
					Graphisme : Julie Zentkowski
					 </br>
					 </br>
					Merci tout particulièrement à Jules Bonnard et Pierre Romera pour leur aide précieuse en code.
					 </br>
					 </br>
					Remerciements : 
					Robin Meier, Daniele Ghisi, João Felipe, Anthony Rival, Dipty Chander 
					 </br>
					 </br>
					Hello Shadow 
					 </br>
					Composed by Stromae, SKYGGE, The Bionix with Flow Machines, inspired by Cape Verdian music, Audio stems generated: choirs, rhythm guitar, 
					 </br>
					Lyrics: Kiesza
					 </br>
					Vocals: Kiesza, All instruments performed by Stromae, The Bionix and SKYGGE
					 </br>
					Mixed by Lionel Capouillez, Produced by The Bionix
					 </br>
					 </br>
					Sons NSynth
					 </br>
					License / Copyright 2017 Google Inc.
					 </br>
					 </br>
					DeepBach: harmonization in the style of Bach generated using deep learning
					 </br>
					DeepBach is developed by Gaëtan Hadjeres,  Sony CSL and LIP6 (UPMC/CNRS).
					 </br>
					Performed by Emmanuel Deruty using Küng recorders. Flow Machines project is funded by the European Research Council under the Seventh Framework Programme / ERC Grant Agreement n. 291156
					 </br>
					Daddy's Car: a song composed by Artificial Intelligence - in the style of the Beatles
					 </br> 
					Composed with Flow Machines and 45 songs of The Beatles. Scientists at SONY CSL Research Lab  have created the first-ever entire songs composed by Artificial Intelligence: "Daddy's Car" and "Mister Shadow". "Daddy's Car"  is composed in the style of The Beatles. French composer Benoît Carré arranged and produced the songs, and wrote the lyrics. 
					 </br>
					 </br>
					Jimmy O'Corlan
					 </br>
					João Felipe, char-rnn composes Irish Folk music. Samples generated by char-rnn when trained on ~14k Irish Folk tunes (downloaded from thesession.org).
					 </br>
					http://www.seaandsailor.com ; https://twitter.com/seaandsailor 
					 </br>
					 </br>
					As the lights fade out 
					 </br>
					Daniele Ghisi, Robin Meier, Commissioned by IRCAM-Centre Pompidou, Used, in part, in "La fabrique de monstres", a theatrical piece by Jean-François Peyret.
					 </br>
					With the help of Philippe Esling, Léopold Créstel, Mattia Bergomi, Giorgio Presti, NaMi Lab
					 </br>
					Obtained via a modified version of the SampleRNN model (Soroush Mehri et al. link), followed by a selection of results and a rough montage.
					 </br>
					 </br>
					La Marche Turque
					 </br>
					W.A. Mozart
					 </br>
					 </br>
					Pierre et le Loup
					 </br>
					Sergueï Prokofiev
					 </br>
					 </br>
					Icône « iMac » par Vladimir Belochkin, de thenounproject.com
					 </br>
					Emission SOFT POWER par Frédéric Martel et Zoé Sfez - France Culture 
					 </br>
					Invité François Pachet, Director of Spotify Creator Technology Research Lab
					 </br>
					“À l'occasion des Grammys Awards 2018, Soft Power s'intéresse aux mutations du secteur musical et à l'impact de l'intelligence artificielle sur la création. L'IA remplacera-t-elle les artistes ?”
					 </br>
					https://www.franceculture.fr/emissions/soft-power/soft-power-dimanche-28-janvier-2018  
					 </br>
					Stromae et d'autres artistes composent "Hello World" avec... de l'intelligence artificielle
					 </br>
					Par Culturebox (avec AFP) @Culturebox
					 </br>
					https://culturebox.francetvinfo.fr/musique/evenements/stromae-et-kiesza-dans-un-album-realise-avec-de-l-intelligence-artificielle-266239 
					Images Deep Dream générées à partir de http://psychic-vr-lab.com/deepdream/ 
				</p>
			</div>
			<div v-else-if="parcours === 'juriste'">			
				<p>
					GENERIQUE
					 </br>
					 Graphisme : Julie Zentkowski
					 </br>
					 </br>
					 Merci tout particulièrement à Jules Bonnard et Pierre Romera de l'AFP pour leur aide précieuse en code
					 </br>
					 </br>
					 Remerciements :
					 </br>
					 Jacques Levy-Vehel (co-fondateur de Case Law Analytics et chercheur à l'Institut national de recherche en informatique et en automatique)
					 Joachim Herrera (doctorant à l'Ecole de droit de Sciences Po)
					 </br>
					 Antoine Garapon (magistrat et juriste; Secrétaire général de l'Institut des hautes études sur la Justice)
					 </br>
					 Lise Damelet (avocate chez Orrick, Herrington & Sutcliffe, cofondatrice de l'Incubateur du barreau de Paris)
					 </br>
					 Dipty Chander (Présidente E-mma France)
					 </br>
					 Icône « iMac » par Vladimir Belochkin, de thenounproject.com
				</p>
			</div>


			<div class="credits-footer">
				<social-sharing inline-template class="mb-4">
					<div>
						<network network="facebook" class="btn btn-sm btn-default">
						  <i class="fa fa-fw fa-facebook"></i> Facebook
						</network>
						<network network="googleplus" class="btn btn-sm btn-default">
						  <i class="fa fa-fw fa-google-plus"></i> Google +
						</network>
						<network network="linkedin" class="btn btn-sm btn-default">
						  <i class="fa fa-fw fa-linkedin"></i> LinkedIn
						</network>
						<network network="twitter" class="btn btn-sm btn-default">
						  <i class="fa fa-fw fa-twitter"></i> Twitter
						</network>
					</div>
				</social-sharing>
				<div class="text-center mt-4">
					<router-link to="/" class="btn btn-primary">
						Refaire une partie
					</router-link>
				</div>
			</div>
		</div>
	</div>
</template>

<script>
module.exports = {
	name: 'credits',
	props: ['parcours'],
	computed: {
		animationDuration: function() {
			return ({
				'juriste': 10,
				'musicien': 10,
				'conducteur': 10
			}[this.parcours] || 30) + 's';
		}
	}
}
</script>

<style scoped>
.credits {
	position:absolute;
	top: 0;
	left: 50%;
	height: 100%;	
	width: 100%;
	max-width: 660px;
	transform: translateX(-50%);
	overflow: hidden;
}

.wrapper {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  font-family: 'Roboto', sans-serif;
  font-size: 15px;
  text-align: center;
  animation: 30s credits linear forwards;
}

.credits-footer {
	position: absolute
	top:100%;
	left:0;
	width: 100%;
	padding: 10%;
	transform: translateY(100%);
	font-weight: bold;
}

@keyframes credits {
    0% { 
    	top:  100%;
    	transform: translateY(0);
    }
  	100% { 
  		top: 0; 
    	transform: translateY(-100%);
  	}
 }
</style>